ServicosOnline/grails-app/domain/br/com/servicosonline/CategoriaServico.groovy
package br.com.servicosonline

class CategoriaServico {
	
	static searchable = true
	
	String nome
	
	byte[] icone
	String iconeType
	
	static hasMany = [quesitos: Quesito]

    static constraints = {
		icone(nullable:true, maxSize: 4096000 /* 4000K */)
		iconeType(nullable:true)
    }
	
	String toString() {
		nome
	}
}

ServicosOnline/grails-app/domain/br/com/servicosonline/PrestadorServico.groovy
package br.com.servicosonline

class PrestadorServico {
	
	static searchable = true
		
	String nome
	TipoPrestadorServico tipoPrestadorServico
	String email
//	String endereco
	String complemento
//	Integer numero
//	String bairro
//	String cep
//	Estado estado
//	Cidade cidade
	String telefoneResidencial
	String telefoneComercial
	String celular
	
	String txtLogradouro	
	String txtNumero
	String txtBairro
	String txtCEP
	String txtEstado
	String txtUF
	String txtCidade	
	String txtEndereco
	String txtLatitude
	String txtLongitude
	String txtRetornoCompleto
	
	BigDecimal media
	
	Integer destaque
	
	byte[] avatar
	String avatarType
				
	static hasMany = [categoriasServico: CategoriaServico]

    static constraints = {
		complemento(nullable:true)
		telefoneResidencial(nullable:true)
		telefoneComercial(nullable:true)
		celular(nullable:true)
		media(nullable:true)
		
		avatar(nullable:true, maxSize: 4096000 /* 4000K */)
		avatarType(nullable:true)
    }
	
	String toString() {
		nome
	}
	
	Boolean jaCurtiu(){
		PrestadorServicoController prestadorServicoController = new PrestadorServicoController()		
		return prestadorServicoController.jaCurtiu(id)
	}
	
	Boolean jaAvaliou(){
		PrestadorServicoController prestadorServicoController = new PrestadorServicoController()		
		return prestadorServicoController.jaAvaliou(id)
	}
	
	Number getNuCurtidas() {
		PrestadorServicoController prestadorServicoController = new PrestadorServicoController()
		return prestadorServicoController.getNuCurtidas(id)		 
	}
	
	Number getNuDescurtidas() {
		PrestadorServicoController prestadorServicoController = new PrestadorServicoController()
		return prestadorServicoController.getNuDescurtidas(id)
	}
	
	Number getMediaAvaliacoes() {
		PrestadorServicoController prestadorServicoController = new PrestadorServicoController()
		return prestadorServicoController.getMediaAvaliacoes(id)
	}
	
	Boolean ehFavorito(){
		PrestadorServicoController prestadorServicoController = new PrestadorServicoController()
		return prestadorServicoController.ehFavorito(id)
	}
}

ServicosOnline/grails-app/domain/br/com/servicosonline/Usuario.groovy
package br.com.servicosonline

class Usuario {

	transient springSecurityService
	
	static searchable = true

	String username
	String password
	boolean enabled
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired
	
	String nome
	String email
	String endereco
	String complemento
	Integer numero
	String bairro
	String cep
	Estado estado
	Cidade cidade
	String telefoneResidencial
	String telefoneComercial
	String celular
	
	String facebookUser
		
	byte[] avatar
	String avatarType
		
	static hasMany = [usuarios: Usuario, usuariosNegados: Usuario]

	static constraints = {
		username blank: false, unique: true
		password blank: false
		facebookUser nullable:true
		
		email(nullable:true)
		cidade(nullable:true)
		estado(nullable:true)
		nome(nullable:true)
		
		
		endereco(nullable:true)
		complemento(nullable:true)
		numero(nullable:true)
		bairro(nullable:true)
		cep(nullable:true)
		telefoneResidencial(nullable:true)
		telefoneComercial(nullable:true)
		celular(nullable:true)
		
		email(unique:true)
//		password(password:true)
		avatar(nullable:true, maxSize: 4096000 /* 4000K */)
		avatarType(nullable:true)
	}

	static mapping = {
		password column: '`password`'		
	}

	Set<Papel> getAuthorities() {
		UsuarioPapel.findAllByUsuario(this).collect { it.papel } as Set
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}
	
	String toString() {
		nome
	}
			
	Integer verificarRelacionamento(){
		UsuarioController usuarioController = new UsuarioController()
		return usuarioController.verificarRelacionamento(id)
	}	
}

ServicosOnline/grails-app/views/categoriaServico/_form.gsp
<%@ page import="br.com.servicosonline.CategoriaServico" %>



<div class="fieldcontain ${hasErrors(bean: categoriaServicoInstance, field: 'nome', 'error')} required">
	<label for="nome">
		<g:message code="categoriaServico.nome.label" default="Nome" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nome" value="${categoriaServicoInstance?.nome}" required="true"/>
</div>

<div class="fieldcontain ${hasErrors(bean: categoriaServicoInstance, field: 'quesitos', 'error')} required">
	<label for="quesitos">
		<g:message code="categoriaServico.quesitos.label" default="Quesitos" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="quesitos" from="${br.com.servicosonline.Quesito.list()}" multiple="multiple" optionKey="id" size="5" value="${categoriaServicoInstance?.quesitos*.id}" class="many-to-many" optionValue="nome" required="true"/>
</div>

<g:if test="${categoriaServicoInstance?.icone}">
	<div class="fieldcontain">
		<span id="image-label" class="property-label"><g:message code="categoriaServico.icone.label" default="" /></span>
		<span class="property-value" aria-labelledby="image-label"><img class="icone_small" src="${createLink(action:'icone_image', id:categoriaServicoInstance?.id)}" /></span>					
	</div>
	
	<div class="fieldcontain ${hasErrors(bean: categoriaServicoInstance, field: 'icone', 'error')}">
		<label for="avatar">
			<g:message code="categoriaServico.icone.label" default="Ícone (4MB)" />

		</label>
		<input type="file" name="icone" id="icone" />
	</div>
</g:if>
<g:else>
	<div class="fieldcontain ${hasErrors(bean: categoriaServicoInstance, field: 'icone', 'error')} required">
		<label for="avatar">
			<g:message code="categoriaServico.icone.label" default="Ícone (4MB)" />
			<span class="required-indicator">*</span>
		</label>
		<input type="file" name="icone" id="icone" required="required" />
	</div>
</g:else>

ServicosOnline/grails-app/views/categoriaServico/create.gsp
<%@ page import="br.com.servicosonline.CategoriaServico" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'categoriaServico.label', default: 'Categoria de Serviço')}" />
		<g:set var="entitiesName" value="${message(code: 'categoriasServico.label', default: 'Categorias de Serviço')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-categoriaServico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="home" controller="categoriaServico" action="list"><g:message code="default.home.label"/></g:link></li>
				<li><g:link class="favorito" controller="favorito" action="list" params="[byuser:1]"><g:message code="default.favorito.label" default="Favoritos"/></g:link></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-categoriaServico" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${categoriaServicoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${categoriaServicoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
<%--			<g:form action="save" >--%>
			<g:uploadForm action="save">
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
				<g:hiddenField name="view" value="create"/>
			</g:uploadForm>	
<%--			</g:form>--%>
		</div>
	</body>
</html>

ServicosOnline/grails-app/views/categoriaServico/edit.gsp
<%@ page import="br.com.servicosonline.CategoriaServico" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'categoriaServico.label', default: 'Categoria de Serviço')}" />
		<g:set var="entitiesName" value="${message(code: 'categoriasServico.label', default: 'Categorias de Serviço')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-categoriaServico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="home" controller="categoriaServico" action="list"><g:message code="default.home.label"/></g:link></li>
				<li><g:link class="favorito" controller="favorito" action="list" params="[byuser:1]"><g:message code="default.favorito.label" default="Favoritos"/></g:link></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
				<sec:ifAnyGranted roles="ROLE_ADMIN">
					<li><g:link class="create" action="create"><g:message code="default.nova.label" args="[entityName]" /></g:link></li>
				</sec:ifAnyGranted>	
			</ul>
		</div>
		<div id="edit-categoriaServico" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${categoriaServicoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${categoriaServicoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
<%--			<g:form method="post" >--%>
			<g:uploadForm action="update">
				<g:hiddenField name="id" value="${categoriaServicoInstance?.id}" />
				<g:hiddenField name="version" value="${categoriaServicoInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
				<g:hiddenField name="view" value="edit"/>
			</g:uploadForm>	
<%--			</g:form>--%>
		</div>
	</body>
</html>

ServicosOnline/grails-app/views/categoriaServico/list.gsp
<%@ page import="br.com.servicosonline.CategoriaServico" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'categoriaServico.label', default: 'Categoria de Serviço')}" />
		<g:set var="entitiesName" value="${message(code: 'categoriasServico.label', default: 'Categorias de Serviço')}" />
		<title><g:message code="default.list.label" args="[entitiesName]" /></title>
	</head>
	<body>
		<a href="#list-categoriaServico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="home" controller="categoriaServico" action="list"><g:message code="default.home.label"/></g:link></li>
				<li><g:link class="favorito" controller="favorito" action="list" params="[byuser:1]"><g:message code="default.favorito.label" default="Favoritos"/></g:link></li>
				<sec:ifAnyGranted roles="ROLE_ADMIN">
					<li><g:link class="create" action="create"><g:message code="default.nova.label" args="[entityName]" /></g:link></li>
				</sec:ifAnyGranted>
			</ul>
		</div>
		<div id="list-categoriaServico" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entitiesName]" /></h1>
			
			<br>
			<div class="nav">
				<g:form action="search" method="get">
		            <g:textField name="q" value="${params.q}" required="true"/>
		            <g:submitButton name="search" value="Buscar"/>
		        </g:form>
		    </div>
			<br>
			
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<th><g:message code="categoriaServico.icone.label" default="Ícone" /></th>
					
						<th><g:message code="categoriaServico.nome.label" default="Nome" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${categoriaServicoInstanceList}" status="i" var="categoriaServicoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td style="text-align: center;">
							<g:link action="show" id="${categoriaServicoInstance.id}"><span class="property-value" aria-labelledby="image-label"><img class="icone_small" src="${createLink(controller:'categoriaServico', action:'icone_image', id:categoriaServicoInstance?.id)}" /></span></g:link>					
						</td>
					
						<td style="text-align: center;"><g:link action="show" id="${categoriaServicoInstance.id}">${fieldValue(bean: categoriaServicoInstance, field: "nome")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${categoriaServicoInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

ServicosOnline/grails-app/views/categoriaServico/search.gsp
<%@ page import="br.com.servicosonline.CategoriaServico" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'categoriaServico.label', default: 'Categoria de Serviço')}" />
		<g:set var="entitiesName" value="${message(code: 'categoriasServico.label', default: 'Categorias de Serviço')}" />
		<title><g:message code="default.search.label" args="[entitiesName]" /></title>
	</head>
	<body>
		<a href="#list-categoriaServico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="home" controller="categoriaServico" action="list"><g:message code="default.home.label"/></g:link></li>
				<li><g:link class="favorito" controller="favorito" action="list" params="[byuser:1]"><g:message code="default.favorito.label" default="Favoritos"/></g:link></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
				<sec:ifAnyGranted roles="ROLE_ADMIN">
					<li><g:link class="create" action="create"><g:message code="default.nova.label" args="[entityName]" /></g:link></li>
				</sec:ifAnyGranted>	
			</ul>
		</div>
		<div id="list-categoriaServico" class="content scaffold-list" role="main">
			<h1><g:message code="default.search.label" args="[entitiesName]" /></h1>
			
			<br>
			<div class="nav">
				<g:form action="search" method="get">
		            <g:textField name="q" value="${params.q}" required="true"/>
		            <g:submitButton name="search" value="Buscar"/>
		        </g:form>
		    </div>
			<br>
			
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			
			<g:set var="haveQuery" value="${params.q?.trim()}" />
			<g:set var="haveResults" value="${searchResult?.results}" />
	
			<g:if test="${haveResults}">
				<div class="list">
					<table>
						<thead>
							<tr>
								
								<th><g:message code="categoriaServico.icone.label" default="Ícone" /></th>
							
								<g:sortableColumn property="nome" title="${message(code: 'categoriaServico.nome.label', default: 'Nome')}" />
							
							</tr>
						</thead>
						<tbody>
						<g:set var="totalPages"	value="${Math.ceil(searchResult.total / searchResult.max)}" />
						<g:each in="${searchResult.results}" status="i" var="categoriaServicoInstance">
							<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
							
								<td style="text-align: center;">
									<span class="property-value" aria-labelledby="image-label"><img class="icone_small" src="${createLink(controller:'categoriaServico', action:'icone_image', id:categoriaServicoInstance?.id)}" /></span>					
								</td>
							
								<td><g:link action="show" id="${categoriaServicoInstance.id}">${fieldValue(bean: categoriaServicoInstance, field: "nome")}</g:link></td>
							
							</tr>
						</g:each>
						</tbody>
					</table>
				</div>	
			</g:if>
			<g:else>
				<div class="no_results">
					<g:message code="search.no.result.label" default="Nenhum resultado encontrado..."/>
				</div>
			</g:else>
			<div class="pagination">
				<g:paginate params="[q: params.q]" total="${searchResult.total}" />
			</div>
		</div>
	</body>
</html>

ServicosOnline/grails-app/views/categoriaServico/show.gsp
<%@page import="br.com.servicosonline.PrestadorServicoController"%>
<%@ page import="br.com.servicosonline.CategoriaServico" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'categoriaServico.label', default: 'Categoria de Serviço')}" />
		<g:set var="entitiesName" value="${message(code: 'categoriasServico.label', default: 'Categorias de Serviço')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    	<meta charset="utf-8">
    	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    	<script>
			var map;
			function initialize(lat, lng, zoom) {
				var myLatLng = new google.maps.LatLng(lat, lng, zoom);
  				var mapOptions = {
    				zoom: zoom,
    				center: myLatLng
  				};
  				map = new google.maps.Map(document.getElementById('map-canvas'),
      				mapOptions);  	
			}

			function setMarker(lat, lng, zoom, title, imageURL){
				var image = 'http://localhost:8080' + imageURL;				
				var myLatLng = new google.maps.LatLng(lat, lng, zoom);
  			  	var marker = new google.maps.Marker({
  			    	position: myLatLng,
  			      	map: map,
  			      	icon: image,
  			      	title: title
  			  	});	
			}

			function setCenter(lat, lng, zoom){
				var myLatLng = new google.maps.LatLng(lat, lng, zoom);
				map.setCenter(myLatLng);
				location.hash = "map";
			}

    	</script>	
	</head>
	<body>
		<a href="#show-categoriaServico" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="home" controller="categoriaServico" action="list"><g:message code="default.home.label"/></g:link></li>
				<li><g:link class="favorito" controller="favorito" action="list" params="[byuser:1]"><g:message code="default.favorito.label" default="Favoritos"/></g:link></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entitiesName]" /></g:link></li>
				<sec:ifAnyGranted roles="ROLE_ADMIN">
					<li><g:link class="create" action="create"><g:message code="default.nova.label" args="[entityName]" /></g:link></li>
				</sec:ifAnyGranted>	
			</ul>
		</div>
		<div id="show-categoriaServico" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list categoriaServico">
			
				<li class="fieldcontain">
					<span id="image-label" class="property-label"><g:message code="categoriaServico.icone.label" default="" /></span>
						<span class="property-value" aria-labelledby="image-label"><img class="icone_small" src="${createLink(action:'icone_image', id:categoriaServicoInstance?.id)}" /></span>					
  				</li>
			
				<g:if test="${categoriaServicoInstance?.nome}">
				<li class="fieldcontain">
					<span id="nome-label" class="property-label"><g:message code="categoriaServico.nome.label" default="Nome" /></span>
					
						<span class="property-value" aria-labelledby="nome-label"><g:fieldValue bean="${categoriaServicoInstance}" field="nome"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${categoriaServicoInstance?.quesitos}">
				<li class="fieldcontain">
					<span id="quesitos-label" class="property-label"><g:message code="categoriaServico.quesitos.label" default="Quesitos" /></span>
					
						<g:each in="${categoriaServicoInstance.quesitos}" var="q">
						<span class="property-value" aria-labelledby="quesitos-label"><g:link controller="quesito" action="show" id="${q.id}">${q?.nome}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<sec:ifAnyGranted roles="ROLE_ADMIN">
				<g:form>
					<fieldset class="buttons">
						<g:hiddenField name="id" value="${categoriaServicoInstance?.id}" />
						<g:link class="edit" action="edit" id="${categoriaServicoInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
						<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
					</fieldset>
				</g:form>
			</sec:ifAnyGranted>	
		</div>
									
		<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
		</g:if>
			
			<br>
			<div class="nav">
				<g:form controller="prestadorServico" action="search" method="get">
		            <g:message code="categoriaServico.prestadorServico.label" default="Prestador" />
		            <g:textField name="q" value="${params.q}"/>
		            <g:hiddenField name="categoriaServicoId" value="${categoriaServicoInstance?.id}" />
		            		            
		            <g:message code="usuario.estado.label" default="Estado" />
					<g:select id="estado" name="estado.id" from="${br.com.servicosonline.Estado.list()}" optionKey="id" required="" value="${usuarioInstance?.estado?.id}" class="many-to-one"  noSelection="['':'Selecione um estado...']" onchange="${remoteFunction(controller: 'cidade', action: 'buscaCidades', params: '\'estado=\' + this.value', update:'cidadeSelect')}" optionValue="nome"/>
				
					<g:message code="usuario.cidade.label" default="Cidade" />
					<div id="cidadeSelect" style="display: inline;">
						<g:render template="/cidade/cidade" model="[cidades: cidades, cidade:usuarioInstance?.cidade?.id]" ></g:render>
					</div>
		            
		            <g:submitButton name="search" value="Buscar"/>
		        </g:form>
		    </div>
						
			<br>
			
			
			<g:if test="${prestadorServicoDestaqueInstanceListTotal > 0}">
				<div class="destaques"><span class="destaques_titulo"><g:message code="prestadorServico.destaques.patrocinados.label" default="Destaques Patrocinados" /></span>			
					<g:each in="${prestadorServicoDestaqueInstanceList}" status="i" var="prestadorServicoDestaqueInstance">
						<g:if test="${(prestadorServicoDestaqueInstance?.txtLatitude != null) && (prestadorServicoDestaqueInstance?.txtLatitude != "")}">
							<script>
								google.maps.event.addDomListener(window, 'load', function() {
									if (${i} == 0){
										initialize(${prestadorServicoDestaqueInstance?.txtLatitude}, ${prestadorServicoDestaqueInstance?.txtLongitude}, 16);
									}
									setMarker(${prestadorServicoDestaqueInstance?.txtLatitude}, ${prestadorServicoDestaqueInstance?.txtLongitude}, 16, '${prestadorServicoDestaqueInstance?.nome}', '${createLink(action:'icone_image', id:categoriaServicoInstance?.id)}');
								});								
							</script>							
						</g:if>
						
						<g:render template="/prestadorServico/prestador" model="[prestadorServicoInstance: prestadorServicoDestaqueInstance, i:i, destaque_class: ' destaque']" ></g:render>
		
					</g:each>
				</div>	
			</g:if>	
			
			<g:each in="${prestadorServicoInstanceList}" status="i" var="prestadorServicoInstance">
				<g:if test="${(prestadorServicoInstance?.txtLatitude != null) && (prestadorServicoInstance?.txtLatitude != "")}">
					<script>
						google.maps.event.addDomListener(window, 'load', function() {
							if ((${i} == 0) && (${prestadorServicoDestaqueInstanceListTotal} == 0)){	
								initialize(${prestadorServicoInstance?.txtLatitude}, ${prestadorServicoInstance?.txtLongitude}, 16);
							}
							setMarker(${prestadorServicoInstance?.txtLatitude}, ${prestadorServicoInstance?.txtLongitude}, 16, '${prestadorServicoInstance?.nome}', '${createLink(action:'icone_image', id:categoriaServicoInstance?.id)}');
						});								
					</script>
					
					<g:render template="/prestadorServico/prestador" model="[prestadorServicoInstance: prestadorServicoInstance, i: i, destaque_class: '']" ></g:render>
																	
				</g:if>
			</g:each>
			
			<g:if test="${prestadorServicoInstanceList.size() == 0}">
					<script>
						var latitudeDefault =  -27.5949884;
						var longitudeDefault = -48.54817430000003;
						var zoomDefault = 16;
												  
						google.maps.event.addDomListener(window, 'load', function() {
							initialize(latitudeDefault, longitudeDefault, 16);
							if(navigator.geolocation) {
								navigator.geolocation.getCurrentPosition(function(position) {
							    	latitudeDefault = position.coords.latitude;
							    	longitudeDefault = position.coords.longitude;    			
							    	initialize(latitudeDefault,longitudeDefault,16,false);
							    });
							}													
						});								
					</script>
			</g:if>
				
			
			<g:each in="${prestadorServicoInstanceListAll}" status="i" var="prestadorServicoInstance">
				<script>
					google.maps.event.addDomListener(window, 'load', function() {
						setMarker(${prestadorServicoInstance?.txtLatitude}, ${prestadorServicoInstance?.txtLongitude}, 16, '${prestadorServicoInstance?.nome}', '${createLink(action:'icone_image', id:categoriaServicoInstance?.id)}');
					});
				</script>
			</g:each>
			
			<div class="pagination">
				<g:paginate total="${prestadorServicoInstanceTotal}" params="[id: categoriaServicoInstance.id]" />
			</div>
			
			<a name="map"></a>						
			<div id="map-canvas"></div>
							
	</body>
</html>